# Generated by Django 3.0.3 on 2020-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('translate', models.CharField(choices=[('en', '영어'), ('ja', '일본어'), ('zh-CN', '중국어'), ('es', '스페인어'), ('fr', '프랑스어'), ('de', '독일어'), ('ru', '러시아어'), ('vi', '베트남어')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
