# Generated by Django 3.0.3 on 2020-02-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Translate',
        ),
    ]
